name: test-CI

on: [push]

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - name: install just
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          Remove-Item .\install.ps1
          scoop update
          scoop install main/xmake main/just main/busybox
      - uses: actions/checkout@v4
      - name: 
        shell: powershell
        run: |
          $env:path+=";$Home\scoop\shims"
          just init
          just config
          just test

  windows-mingw:
    runs-on: windows-latest
    steps:
      - name: Install dependency
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            git
            p7zip
      - uses: actions/checkout@v4
      - name: install just
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          Remove-Item .\install.ps1
          scoop update
          scoop install main/xmake main/just main/busybox
      - name: build
        shell: msys2 {0}
        run: |
          export PATH="$PATH:/c/Users/$USER/scoop/shims"
          just init
          just config
          just test
  osx:
    name: macos build
    runs-on: macos-latest
    steps:
      - name: install-xmake
        run: |
          brew install xmake just
          xmake --version
      - uses: actions/checkout@v4
      - name: build
        run: |
          just init
          just config
          just test
  linux:
    name: linux build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install-xmake
        run: |
          ./scripts/xmake-install.sh xmake-amd64.deb
          sudo apt-get install -y ./xmake-amd64.deb
          rm ./xmake-amd64.deb
          xmake --version
      - name: install just
        uses: extractions/setup-just@v1
      - name: build
        run: |
          just init
          just config
          just test
